#!/usr/bin/env perl
# This is a Mojolicious app, specifically a Lite app
use Mojolicious::Lite;

# Path to project-specific libraries
use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/lib" }

# Load libraries
use Lingua::31337;

# This is just to show a dynamic route, outside of the magical route
get '/inline' => {inline => '<%= scalar localtime %>'};
get '/data' => 'data';

# The typical "index" route, currently redirects to a specific presi
# TODO:
#   - generate an index of available presi's?
#   - do something like remarkise to turn any md into presi
#   - provide an editor for creating a new presi
get '/' => sub { shift->redirect_to('/prog1') };

# This is the magical route that handles all the different presentations
# A controller finds its assets in a templates directory by the same same,
# decamelized
get '/:action' => {controller => 'Slides'};

# This is to show logging capabilities, as well as inform you every time
# morbo restarts due to changed files
app->log->info("start");

# Start the Mojo Webserver and serve this Mojolicious app
app->start;

# These are embedded templates, but as a project grows you'll probably want to
# move each file into templates/
###############################################################################
__DATA__

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>

@@ layouts/querystring.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><hr><%= content %><hr></body>
</html>

@@ data.html.ep
% layout param('layout') ? 'querystring' : 'default';
% title 'Time';
<strong><%= scalar localtime %></strong>